# Site Settings

title: 一些通知
description: 一些通知。
url: "https://haobit.top"
baseurl: /some-notices

lang: zh-CN

collections:
  notices:
    output: true

defaults:
  - scope:
      path: ""
      type: "notices"
    values:
      layout: notices
      permalink: /:name/

# Build Settings

theme: jekyll-theme-cayman
github:
  is_project_page: false
plugins:
  - jekyll-feed
  - jekyll-target-blank

feed:
  collections:
    notices:
      path: "/feed.atom"

exclude:
  - ReadMe.md
  - scripts/
